- name: Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.exapmle.com
  tasks:
    - name: Access a variable
      ansoble.builtin.debug:
         msg: URL == {{URL}}  
